name: test0002
favicon: null
layout_spectrum: 0.860584317240864
typography_spectrum: 0.5264982429798692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff2f4'
    - '#009fe3'
    - '#c3c9c7'
    - '#6c7c79'
    - '#343434'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
